require: rubocop-rspec

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

RSpec/MultipleExpectations:
  Max: 4

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'node_modules/**/*'
