version: 2.1
services:
  app:
    build:
      context: .
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    depends_on:
      - webdriver_chrome
    command: bin/rails s -b 0.0.0.0 -p 3000
  webdriver_chrome:
    image: selenium/standalone-chrome
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.7.2
        environment:
          PGHOST: localhost
          PGUSER: bookstore
          RAILS_ENV: test
      - image: postgres:9.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bookstore_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: install nodejs
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
            NVM_DIR="$HOME/.nvm"
            echo "export NVM_DIR=\"$HOME/.nvm\"" >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
            source $BASH_ENV
            nvm install \
            node 
      - run:
          name: install yarn
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update
            sudo apt-get install yarn -y 
            yarn install

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle exec rake db:migrate

      # run tests!
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run tests
          command: bundle exec rspec
